# Python codes for recomendation system to determine ratings based on user id

In [1]:
# Import Python libraries

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Load Dataset

In [4]:
Col_names = ['User_id', 'Movie_id', 'Ratings', 'Unique_timestamp']
Ratings = pd.read_csv('ml-100k/u.data', sep = '\t', names = Col_names, encoding = 'latin-1')
Ratings

       User_id  Movie_id  Ratings  Unique_timestamp
0          196       242        3         881250949
1          186       302        3         891717742
2           22       377        1         878887116
3          244        51        2         880606923
4          166       346        1         886397596
...        ...       ...      ...               ...
99995      880       476        3         880175444
99996      716       204        5         879795543
99997      276      1090        1         874795795
99998       13       225        2         882399156
99999       12       203        3         879959583

[100000 rows x 4 columns]

In [5]:
N_Users = Ratings.User_id.unique().shape[0]
print(f"There are {N_Users} in the dataset")

There are 943 in the dataset

In [6]:
# Create pivot table based on user id, movie id and rating

In [7]:
Pivot_table = Ratings.pivot_table (index = 'User_id', columns = 'Movie_id', values = 'Ratings')
Pivot_table

Movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
User_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Replace Nan with 0

In [9]:
Data_matrix = Pivot_table.replace(np.nan, 0)
Data_matrix

Movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
User_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
# Find cosine similarity for users

In [11]:
from sklearn.metrics.pairwise import pairwise_distances
User_similarity = pairwise_distances(Data_matrix, metric = 'cosine')
User_similarity

array([[1.33226763e-15, 8.33069016e-01, 9.52540457e-01, ...,
        8.51383057e-01, 8.20492117e-01, 6.01825261e-01],
       [8.33069016e-01, 0.00000000e+00, 8.89408675e-01, ...,
        8.38515222e-01, 8.27732187e-01, 8.94202122e-01],
       [9.52540457e-01, 8.89408675e-01, 0.00000000e+00, ...,
        8.98757435e-01, 8.66583851e-01, 9.73444131e-01],
       ...,
       [8.51383057e-01, 8.38515222e-01, 8.98757435e-01, ...,
        0.00000000e+00, 8.98358201e-01, 9.04880419e-01],
       [8.20492117e-01, 8.27732187e-01, 8.66583851e-01, ...,
        8.98358201e-01, 0.00000000e+00, 8.17535338e-01],
       [6.01825261e-01, 8.94202122e-01, 9.73444131e-01, ...,
        9.04880419e-01, 8.17535338e-01, 0.00000000e+00]])

In [12]:
# Score calculation

In [13]:
def prediction(Ratings, Similarity, type = 'user'):
    User_ratings_mean = Ratings.mean(axis = 1).to_numpy()
    Ratings_diff = Ratings - User_ratings_mean [:, np.newaxis]
    Predict = User_ratings_mean [:, np.newaxis] + Similarity.dot(Ratings_diff) / np.abs(Similarity).sum(axis=1)[:, np.newaxis]        
    return Predict

In [14]:
# Prediction table

In [15]:
User_prediction = prediction(Data_matrix, User_similarity, type = 'user')
User_prediction

array([[ 2.06532606,  0.73430275,  0.62992381, ...,  0.39359041,
         0.39304874,  0.3927712 ],
       [ 1.76308836,  0.38404019,  0.19617889, ..., -0.08837789,
        -0.0869183 , -0.08671183],
       [ 1.79590398,  0.32904733,  0.15882885, ..., -0.13699223,
        -0.13496852, -0.13476488],
       ...,
       [ 1.59151513,  0.27526889,  0.10219534, ..., -0.16735162,
        -0.16657451, -0.16641377],
       [ 1.81036267,  0.40479877,  0.27545013, ..., -0.00907358,
        -0.00846587, -0.00804858],
       [ 1.8384313 ,  0.47964837,  0.38496292, ...,  0.14686675,
         0.14629808,  0.14641455]])

In [16]:
# Finding similarity among users

In [17]:
# Selection of input users
Input_users = 34

In [18]:
# Convert user sim table into dataframe
User_Sim_Table = pd.DataFrame(User_similarity)
User_Sim_Table

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,1.332268e-15,0.833069,0.952540,0.935642,0.621525,0.569761,0.559633,0.680928,0.921862,0.623456,...,0.630473,0.880518,0.725124,0.810295,0.802674,0.881905,0.685928,0.851383,0.820492,0.601825
1,8.330690e-01,0.000000,0.889409,0.821879,0.927021,0.754157,0.892672,0.896656,0.838952,0.840138,...,0.843014,0.692058,0.641211,0.575954,0.680111,0.771417,0.773210,0.838515,0.827732,0.894202
2,9.525405e-01,0.889409,0.000000,0.655849,0.978755,0.927585,0.933863,0.916940,0.938960,0.934849,...,0.968125,0.957247,0.836171,0.930962,0.875755,0.973729,0.838110,0.898757,0.866584,0.973444
3,9.356422e-01,0.821879,0.655849,0.000000,0.968196,0.931956,0.908770,0.811940,0.898716,0.939141,...,0.947893,0.963216,0.866885,0.806529,0.853942,0.969862,0.803142,0.847959,0.829914,0.941248
4,6.215248e-01,0.927021,0.978755,0.968196,0.000000,0.762714,0.626400,0.751070,0.943153,0.798573,...,0.661206,0.919420,0.905076,0.920221,0.851393,0.928541,0.760045,0.860405,0.847503,0.686059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,8.819047e-01,0.771417,0.973729,0.969862,0.928541,0.888148,0.892973,0.904102,0.960148,0.928540,...,0.933961,0.568846,0.741979,0.773551,0.567334,0.000000,0.912313,0.819971,0.956736,0.855750
939,6.859280e-01,0.773210,0.838110,0.803142,0.760045,0.647551,0.670075,0.753117,0.879505,0.657039,...,0.672847,0.892976,0.812464,0.818683,0.824842,0.912313,0.000000,0.854848,0.738624,0.758972
940,8.513831e-01,0.838515,0.898757,0.847959,0.860405,0.855554,0.940007,0.853855,0.856755,0.909695,...,0.953048,0.796699,0.711682,0.765789,0.686600,0.819971,0.854848,0.000000,0.898358,0.904880
941,8.204921e-01,0.827732,0.866584,0.829914,0.847503,0.682672,0.717997,0.824678,0.907503,0.787670,...,0.773560,0.926487,0.910412,0.870446,0.900615,0.956736,0.738624,0.898358,0.000000,0.817535
942,6.018253e-01,0.894202,0.973444,0.941248,0.686059,0.723958,0.605636,0.700191,0.924383,0.778140,...,0.736209,0.789237,0.856747,0.922207,0.797756,0.855750,0.758972,0.904880,0.817535,0.000000

In [19]:
# Finding similarity for user 34 using cosine table
Sim_Input_User = User_Sim_Table[Input_users].sort_values(ascending = True).head(5).index
Sim_Input_User

Index([34, 450, 852, 811, 509], dtype='int64')

In [20]:
# Convert the similarity values into a list
Sim_Input_User = list(Sim_Input_User)
Sim_Input_User

[34, 450, 852, 811, 509]

In [21]:
# Select movie id from ratings table using Similarity_Input_User
Sim_User_MovieID_List = []
for Sim_User in Sim_Input_User:
    Sim = list(Ratings[Ratings['User_id']==Sim_User]['Movie_id'])
    Sim_User_MovieID_List.append(Sim)

In [22]:
len(Sim_User_MovieID_List)

5

In [51]:
print (Sim_User_MovieID_List)

[[312, 242, 690, 310, 259, 299, 245, 332, 329, 286, 1024, 324, 294, 292, 990, 289, 898, 899, 288, 991], [470, 783, 1147, 100, 58, 142, 801, 216, 785, 162, 144, 462, 384, 739, 1269, 179, 38, 659, 252, 1160, 566, 496, 679, 387, 908, 265, 1226, 183, 1037, 194, 902, 1263, 64, 1036, 942, 467, 1212, 97, 762, 143, 583, 480, 846, 561, 487, 2, 237, 39, 778, 815, 708, 400, 495, 382, 518, 110, 1203, 710, 660, 152, 304, 520, 604, 642, 494, 211, 847, 559, 1446, 204, 904, 1092, 281, 526, 139, 200, 367, 553, 523, 685, 478, 177, 742, 1044, 509, 89, 238, 29, 15, 837, 65, 49, 176, 434, 729, 1184, 70, 728, 174, 1047, 723, 477, 419, 689, 582, 270, 7, 155, 12, 774, 383, 488, 145, 401, 301, 468, 157, 771, 650, 288, 95, 1, 154, 1020, 712, 227, 923, 1222, 1152, 101, 395, 1050, 94, 272, 629, 225, 402, 736, 707, 60, 613, 465, 747, 493, 123, 10, 514, 1041, 13, 451, 418, 611, 258, 905, 1479, 502, 792, 131, 673, 56, 940, 1192, 158, 203, 193, 612, 1054, 134, 99, 607, 127, 428, 378, 294, 469, 208, 290, 1030, 632, 663, 878, 132, 751, 1039, 967, 1603, 472, 474, 765, 482, 1261, 614, 700, 92, 928, 589, 591, 385, 282, 305, 275, 873, 195, 299, 153, 381, 231, 865, 484, 1033, 199, 311, 433, 1140, 315, 790, 371, 357, 1172, 1401, 354, 54, 558, 241, 1402, 207, 550, 637, 414, 340, 506, 313, 1221, 283, 692, 80, 66, 222, 647, 192, 549, 136, 610, 35, 507, 490, 510, 164, 135, 735, 245, 842, 714, 4, 302, 121, 430, 1425, 686, 775, 312, 205, 81, 1286, 525, 77, 921, 1048, 965, 26, 651, 934, 1444, 71, 98, 233, 141, 956, 491, 185, 448, 169, 1441, 1153, 328, 421, 182, 163, 83, 187, 661, 471, 239, 497, 264, 966, 527, 731, 823, 274, 380, 316, 166, 125, 535, 1208, 393, 845, 609, 1091, 1220, 1271, 79, 1116, 278, 969, 277, 1248, 191, 455, 197, 86, 432, 287, 807, 51, 606, 1435, 761, 67, 479, 705, 821, 622, 90, 709, 500, 396, 202, 530, 427, 481, 936, 73, 1028, 112, 503, 716, 82, 126, 373, 280, 292, 422, 869, 476, 443, 832, 226, 939, 608, 631, 167, 693, 431, 1521, 602, 1053, 648, 715, 215, 900, 254, 210, 657, 88, 117, 655, 269, 180, 1163, 794, 951, 568, 28, 633, 87, 1282, 168, 630, 1303, 332, 3, 717, 557, 218, 223, 499, 173, 161, 1119, 229, 704, 416, 417, 483, 505, 528, 570, 1115, 196, 133, 620, 310, 618, 300, 114, 511, 435, 748, 727, 926, 1284, 749, 284, 318, 968, 501, 307, 713, 188, 662, 96, 389, 50, 347, 230, 372, 181, 627, 336, 235, 190, 102, 403, 221, 23, 734, 671, 43, 172, 345, 741, 118, 386, 776, 519, 866, 33, 702, 1135, 485, 273, 76, 492, 750, 1311, 1249, 1107, 260, 1197, 588, 546, 392, 78, 597, 213, 489, 619, 214, 696, 220, 812, 571, 1297, 725, 322, 111, 286, 724, 457, 259, 44, 722, 47, 616, 91, 699, 601, 186, 603, 61, 11, 423, 781, 521, 498, 140, 151, 756, 1112, 59, 69, 366, 1518, 405, 415, 232, 504, 63, 795, 628, 22, 356, 1421, 25, 228, 170, 1126, 516, 1480, 1061, 234, 399, 178, 584, 732, 388, 1490, 654], [685, 473, 408, 323, 118, 257, 151, 546, 127, 597, 289, 820, 930, 678, 841, 515, 181, 7, 405, 260, 840, 50, 681, 274, 1052, 825, 969, 259, 25, 235, 1, 122, 827, 252, 358, 472, 117, 826, 121, 264, 109, 1615, 407, 568, 100, 506, 250, 926, 290], [301, 292, 304, 294, 748, 690, 258, 323, 892, 289, 307, 286, 315, 300, 308, 895, 988, 321, 678, 243, 901], [319, 50, 288, 680, 751, 310, 300, 260, 879, 687, 258, 603, 332, 302, 754, 289, 301, 345, 326, 307, 343, 268, 892, 338, 266, 328, 690, 245, 181, 309, 294, 271, 705]]

In [25]:
# Convert all the lists as a single list
import itertools
Sim_User_MovieID_Single_List = list(itertools.chain.from_iterable(Sim_User_MovieID_List))

In [26]:
len(Sim_User_MovieID_Single_List)

663

In [27]:
Unique_MovieID_Similar_User = set(Sim_User_MovieID_Single_List)

In [28]:
len(Unique_MovieID_Similar_User)

590

In [52]:
# Input movie list compare user watched 
Input_User_Watched_MovieID = list(Ratings[Ratings['User_id']==Input_users]['Movie_id'].values)
print(Input_User_Watched_MovieID)

[312, 242, 690, 310, 259, 299, 245, 332, 329, 286, 1024, 324, 294, 292, 990, 289, 898, 899, 288, 991]

In [30]:
# Create a list to show movie id to users
Recom = []
for per_id in Unique_MovieID_Similar_User:
    if (per_id in Input_User_Watched_MovieID):
        pass
    else:
        Recom.append(per_id)

In [31]:
len(Recom)

570

In [53]:
print(sorted(Recom))

[1, 2, 3, 4, 7, 10, 11, 12, 13, 15, 22, 23, 25, 26, 28, 29, 33, 35, 38, 39, 43, 44, 47, 49, 50, 51, 54, 56, 58, 59, 60, 61, 63, 64, 65, 66, 67, 69, 70, 71, 73, 76, 77, 78, 79, 80, 81, 82, 83, 86, 87, 88, 89, 90, 91, 92, 94, 95, 96, 97, 98, 99, 100, 101, 102, 109, 110, 111, 112, 114, 117, 118, 121, 122, 123, 125, 126, 127, 131, 132, 133, 134, 135, 136, 139, 140, 141, 142, 143, 144, 145, 151, 152, 153, 154, 155, 157, 158, 161, 162, 163, 164, 166, 167, 168, 169, 170, 172, 173, 174, 176, 177, 178, 179, 180, 181, 182, 183, 185, 186, 187, 188, 190, 191, 192, 193, 194, 195, 196, 197, 199, 200, 202, 203, 204, 205, 207, 208, 210, 211, 213, 214, 215, 216, 218, 220, 221, 222, 223, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 237, 238, 239, 241, 243, 250, 252, 254, 257, 258, 260, 264, 265, 266, 268, 269, 270, 271, 272, 273, 274, 275, 277, 278, 280, 281, 282, 283, 284, 287, 290, 300, 301, 302, 304, 305, 307, 308, 309, 311, 313, 315, 316, 318, 319, 321, 322, 323, 326, 328, 336, 338, 340, 343, 345, 347, 354, 356, 357, 358, 366, 367, 371, 372, 373, 378, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 392, 393, 395, 396, 399, 400, 401, 402, 403, 405, 407, 408, 414, 415, 416, 417, 418, 419, 421, 422, 423, 427, 428, 430, 431, 432, 433, 434, 435, 443, 448, 451, 455, 457, 462, 465, 467, 468, 469, 470, 471, 472, 473, 474, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 509, 510, 511, 514, 515, 516, 518, 519, 520, 521, 523, 525, 526, 527, 528, 530, 535, 546, 549, 550, 553, 557, 558, 559, 561, 566, 568, 570, 571, 582, 583, 584, 588, 589, 591, 597, 601, 602, 603, 604, 606, 607, 608, 609, 610, 611, 612, 613, 614, 616, 618, 619, 620, 622, 627, 628, 629, 630, 631, 632, 633, 637, 642, 647, 648, 650, 651, 654, 655, 657, 659, 660, 661, 662, 663, 671, 673, 678, 679, 680, 681, 685, 686, 687, 689, 692, 693, 696, 699, 700, 702, 704, 705, 707, 708, 709, 710, 712, 713, 714, 715, 716, 717, 722, 723, 724, 725, 727, 728, 729, 731, 732, 734, 735, 736, 739, 741, 742, 747, 748, 749, 750, 751, 754, 756, 761, 762, 765, 771, 774, 775, 776, 778, 781, 783, 785, 790, 792, 794, 795, 801, 807, 812, 815, 820, 821, 823, 825, 826, 827, 832, 837, 840, 841, 842, 845, 846, 847, 865, 866, 869, 873, 878, 879, 892, 895, 900, 901, 902, 904, 905, 908, 921, 923, 926, 928, 930, 934, 936, 939, 940, 942, 951, 956, 965, 966, 967, 968, 969, 988, 1020, 1028, 1030, 1033, 1036, 1037, 1039, 1041, 1044, 1047, 1048, 1050, 1052, 1053, 1054, 1061, 1091, 1092, 1107, 1112, 1115, 1116, 1119, 1126, 1135, 1140, 1147, 1152, 1153, 1160, 1163, 1172, 1184, 1192, 1197, 1203, 1208, 1212, 1220, 1221, 1222, 1226, 1248, 1249, 1261, 1263, 1269, 1271, 1282, 1284, 1286, 1297, 1303, 1311, 1401, 1402, 1421, 1425, 1435, 1441, 1444, 1446, 1479, 1480, 1490, 1518, 1521, 1603, 1615]

In [54]:
# Cross-checking the list with Unique_MovieID_Similar_User
print(sorted(Unique_MovieID_Similar_User))

[1, 2, 3, 4, 7, 10, 11, 12, 13, 15, 22, 23, 25, 26, 28, 29, 33, 35, 38, 39, 43, 44, 47, 49, 50, 51, 54, 56, 58, 59, 60, 61, 63, 64, 65, 66, 67, 69, 70, 71, 73, 76, 77, 78, 79, 80, 81, 82, 83, 86, 87, 88, 89, 90, 91, 92, 94, 95, 96, 97, 98, 99, 100, 101, 102, 109, 110, 111, 112, 114, 117, 118, 121, 122, 123, 125, 126, 127, 131, 132, 133, 134, 135, 136, 139, 140, 141, 142, 143, 144, 145, 151, 152, 153, 154, 155, 157, 158, 161, 162, 163, 164, 166, 167, 168, 169, 170, 172, 173, 174, 176, 177, 178, 179, 180, 181, 182, 183, 185, 186, 187, 188, 190, 191, 192, 193, 194, 195, 196, 197, 199, 200, 202, 203, 204, 205, 207, 208, 210, 211, 213, 214, 215, 216, 218, 220, 221, 222, 223, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 237, 238, 239, 241, 242, 243, 245, 250, 252, 254, 257, 258, 259, 260, 264, 265, 266, 268, 269, 270, 271, 272, 273, 274, 275, 277, 278, 280, 281, 282, 283, 284, 286, 287, 288, 289, 290, 292, 294, 299, 300, 301, 302, 304, 305, 307, 308, 309, 310, 311, 312, 313, 315, 316, 318, 319, 321, 322, 323, 324, 326, 328, 329, 332, 336, 338, 340, 343, 345, 347, 354, 356, 357, 358, 366, 367, 371, 372, 373, 378, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 392, 393, 395, 396, 399, 400, 401, 402, 403, 405, 407, 408, 414, 415, 416, 417, 418, 419, 421, 422, 423, 427, 428, 430, 431, 432, 433, 434, 435, 443, 448, 451, 455, 457, 462, 465, 467, 468, 469, 470, 471, 472, 473, 474, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 509, 510, 511, 514, 515, 516, 518, 519, 520, 521, 523, 525, 526, 527, 528, 530, 535, 546, 549, 550, 553, 557, 558, 559, 561, 566, 568, 570, 571, 582, 583, 584, 588, 589, 591, 597, 601, 602, 603, 604, 606, 607, 608, 609, 610, 611, 612, 613, 614, 616, 618, 619, 620, 622, 627, 628, 629, 630, 631, 632, 633, 637, 642, 647, 648, 650, 651, 654, 655, 657, 659, 660, 661, 662, 663, 671, 673, 678, 679, 680, 681, 685, 686, 687, 689, 690, 692, 693, 696, 699, 700, 702, 704, 705, 707, 708, 709, 710, 712, 713, 714, 715, 716, 717, 722, 723, 724, 725, 727, 728, 729, 731, 732, 734, 735, 736, 739, 741, 742, 747, 748, 749, 750, 751, 754, 756, 761, 762, 765, 771, 774, 775, 776, 778, 781, 783, 785, 790, 792, 794, 795, 801, 807, 812, 815, 820, 821, 823, 825, 826, 827, 832, 837, 840, 841, 842, 845, 846, 847, 865, 866, 869, 873, 878, 879, 892, 895, 898, 899, 900, 901, 902, 904, 905, 908, 921, 923, 926, 928, 930, 934, 936, 939, 940, 942, 951, 956, 965, 966, 967, 968, 969, 988, 990, 991, 1020, 1024, 1028, 1030, 1033, 1036, 1037, 1039, 1041, 1044, 1047, 1048, 1050, 1052, 1053, 1054, 1061, 1091, 1092, 1107, 1112, 1115, 1116, 1119, 1126, 1135, 1140, 1147, 1152, 1153, 1160, 1163, 1172, 1184, 1192, 1197, 1203, 1208, 1212, 1220, 1221, 1222, 1226, 1248, 1249, 1261, 1263, 1269, 1271, 1282, 1284, 1286, 1297, 1303, 1311, 1401, 1402, 1421, 1425, 1435, 1441, 1444, 1446, 1479, 1480, 1490, 1518, 1521, 1603, 1615]

In [55]:
# Cross-checking the list with Input_User_Watched_MovieID
print(sorted(Input_User_Watched_MovieID))

[242, 245, 259, 286, 288, 289, 292, 294, 299, 310, 312, 324, 329, 332, 690, 898, 899, 990, 991, 1024]

In [56]:
# Checking common movie list
print(list(set(Unique_MovieID_Similar_User)&set(Input_User_Watched_MovieID)))

[1024, 898, 259, 899, 286, 288, 289, 292, 294, 299, 690, 310, 312, 324, 329, 332, 990, 991, 242, 245]

In [36]:
User_pred = pd.DataFrame(User_prediction)
User_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,2.065326,0.734303,0.629924,1.010669,0.640686,0.476150,1.784569,1.163032,1.513350,0.704478,...,0.394041,0.394434,0.393981,0.392972,0.393344,0.392272,0.394909,0.393590,0.393049,0.392771
1,1.763088,0.384040,0.196179,0.731538,0.225643,0.003892,1.493597,0.876153,1.108467,0.261991,...,-0.086942,-0.085491,-0.087137,-0.088158,-0.087298,-0.089288,-0.087468,-0.088378,-0.086918,-0.086712
2,1.795904,0.329047,0.158829,0.684154,0.173277,-0.035621,1.488230,0.835769,1.135426,0.236383,...,-0.134795,-0.133537,-0.135543,-0.136438,-0.135041,-0.137611,-0.136374,-0.136992,-0.134969,-0.134765
3,1.729951,0.293913,0.127741,0.644932,0.142143,-0.062261,1.437010,0.796249,1.096663,0.211789,...,-0.161413,-0.160220,-0.161542,-0.162586,-0.161634,-0.163877,-0.162283,-0.163080,-0.161442,-0.161248
4,1.796651,0.454474,0.354422,0.763130,0.359539,0.195987,1.547370,0.908904,1.292027,0.437954,...,0.101762,0.102405,0.101923,0.100839,0.101711,0.099951,0.102515,0.101233,0.101075,0.101201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,1.676950,0.346339,0.177518,0.689906,0.199740,0.003297,1.429565,0.830905,1.070986,0.262183,...,-0.092434,-0.091197,-0.092851,-0.093801,-0.092953,-0.094539,-0.092217,-0.093378,-0.092686,-0.092423
939,1.822346,0.419125,0.286430,0.715605,0.294442,0.106633,1.514591,0.853050,1.195304,0.359260,...,0.014060,0.014688,0.014123,0.013060,0.013669,0.011978,0.014065,0.013021,0.013639,0.013796
940,1.591515,0.275269,0.102195,0.624383,0.133762,-0.069553,1.320734,0.765529,1.035088,0.192697,...,-0.166179,-0.164981,-0.166278,-0.167392,-0.166679,-0.168486,-0.166217,-0.167352,-0.166575,-0.166414
941,1.810363,0.404799,0.275450,0.726616,0.281316,0.087068,1.550310,0.850057,1.205745,0.342987,...,-0.008362,-0.007757,-0.008225,-0.009218,-0.008232,-0.010138,-0.008009,-0.009074,-0.008466,-0.008049
942,1.838431,0.479648,0.384963,0.780521,0.388442,0.240998,1.564232,0.946704,1.289865,0.487383,...,0.147027,0.148208,0.147193,0.146199,0.146916,0.145539,0.148194,0.146867,0.146298,0.146415

In [37]:
User_pred_Trans = User_pred.T
User_pred_Trans

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,2.065326,1.763088,1.795904,1.729951,1.796651,1.996889,2.466055,1.693486,1.681165,2.021688,...,1.924844,1.619096,1.891812,1.696368,1.717658,1.676950,1.822346,1.591515,1.810363,1.838431
1,0.734303,0.384040,0.329047,0.293913,0.454474,0.651172,1.099186,0.296285,0.279528,0.650911,...,0.552456,0.311680,0.550513,0.322611,0.431368,0.346339,0.419125,0.275269,0.404799,0.479648
2,0.629924,0.196179,0.158829,0.127741,0.354422,0.528276,1.016489,0.195398,0.121887,0.530669,...,0.451194,0.140613,0.354913,0.144344,0.247851,0.177518,0.286430,0.102195,0.275450,0.384963
3,1.010669,0.731538,0.684154,0.644932,0.763130,0.921054,1.362861,0.612075,0.616094,0.916215,...,0.834176,0.661829,0.893214,0.662304,0.783208,0.689906,0.715605,0.624383,0.726616,0.780521
4,0.640686,0.225643,0.173277,0.142143,0.359539,0.537388,1.006458,0.198638,0.136368,0.531720,...,0.455212,0.166992,0.398759,0.167841,0.283796,0.199740,0.294442,0.133762,0.281316,0.388442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,0.392272,-0.089288,-0.137611,-0.163877,0.099951,0.259848,0.764340,-0.072866,-0.163505,0.263527,...,0.185602,-0.128949,0.095681,-0.143177,-0.009425,-0.094539,0.011978,-0.168486,-0.010138,0.145539
1678,0.394909,-0.087468,-0.136374,-0.162283,0.102515,0.262375,0.766967,-0.070435,-0.161425,0.266037,...,0.188059,-0.126624,0.097792,-0.141018,-0.007085,-0.092217,0.014065,-0.166217,-0.008009,0.148194
1679,0.393590,-0.088378,-0.136992,-0.163080,0.101233,0.261111,0.765654,-0.071651,-0.162465,0.264782,...,0.186831,-0.127786,0.096736,-0.142097,-0.008255,-0.093378,0.013021,-0.167352,-0.009074,0.146867
1680,0.393049,-0.086918,-0.134969,-0.161442,0.101075,0.261061,0.764983,-0.071744,-0.161396,0.264589,...,0.186850,-0.127045,0.097826,-0.140977,-0.007621,-0.092686,0.013639,-0.166575,-0.008466,0.146298
1681,0.392771,-0.086712,-0.134765,-0.161248,0.101201,0.261089,0.765165,-0.071357,-0.161430,0.264781,...,0.186858,-0.126812,0.097654,-0.140965,-0.007369,-0.092423,0.013796,-0.166414,-0.008049,0.146415

In [38]:
User_pred_Trans[34]

0       1.740469
1       0.283366
2       0.114987
3       0.645096
4       0.127844
          ...
1677   -0.183977
1678   -0.182367
1679   -0.183172
1680   -0.181400
1681   -0.181306
Name: 34, Length: 1682, dtype: float64

In [39]:
gg = User_pred_Trans[34]
gg

0       1.740469
1       0.283366
2       0.114987
3       0.645096
4       0.127844
          ...
1677   -0.183977
1678   -0.182367
1679   -0.183172
1680   -0.181400
1681   -0.181306
Name: 34, Length: 1682, dtype: float64

In [40]:
g = pd.DataFrame(gg)

In [41]:
S = g.T
S

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
34,1.740469,0.283366,0.114987,0.645096,0.127844,-0.081329,1.448638,0.794313,1.08901,0.194232,...,-0.181256,-0.180156,-0.181837,-0.182819,-0.181432,-0.183977,-0.182367,-0.183172,-0.1814,-0.181306

In [42]:
S[187].values >= 0.4

array([ True])

In [43]:
# Selection of the highest rate movies that would be selected by the user, based on user prediction
Highest_rated = []
Input_User_Pre = pd.DataFrame(User_pred_Trans[Input_users])
Input_User_Pred = Input_User_Pre.T
for Re in Recom:
    Value = Input_User_Pred[Re].values
    if(Value >= 1):
        Highest_rated.append(Re)

In [44]:
len(Highest_rated)

27

In [45]:
# Securing names
I_Cols = ['Movie id', 'Movie title', 'Release Date', 'Video Release Date', 'IMDb URL', 'unknown', 'Action', 'Adventure', 'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horro', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
Items = pd.read_csv('ml-100k/u.item', sep = '|', names = I_Cols, encoding = 'latin-1')

In [46]:
# Creating movie list based on recommended movie list
Movie_title = []
for MovieID in Highest_rated:
    Movie = Items[Items['Movie id'] == MovieID]['Movie title'].values
    Movie_title.append(Movie)

In [47]:
Movie_title

[array(['Seven (Se7en) (1995)'], dtype=object),
 array(['I.Q. (1994)'], dtype=object),
 array(['Santa Clause, The (1994)'], dtype=object),
 array(['Free Willy (1993)'], dtype=object),
 array(['Sleepless in Seattle (1993)'], dtype=object),
 array(['Aladdin (1992)'], dtype=object),
 array(['Dances with Wolves (1990)'], dtype=object),
 array(['Snow White and the Seven Dwarfs (1937)'], dtype=object),
 array(['Spitfire Grill, The (1996)'], dtype=object),
 array(['Private Benjamin (1980)'], dtype=object),
 array(['Empire Strikes Back, The (1980)'], dtype=object),
 array(['Princess Bride, The (1987)'], dtype=object),
 array(['Apocalypse Now (1979)'], dtype=object),
 array(['GoodFellas (1990)'], dtype=object),
 array(['Henry V (1989)'], dtype=object),
 array(['Sting, The (1973)'], dtype=object),
 array(['Unforgiven (1992)'], dtype=object),
 array(['Field of Dreams (1989)'], dtype=object),
 array(['Breaking the Waves (1996)'], dtype=object),
 array(['Men in Black (1997)'], dtype=object),
 array(['Chasing Amy (1997)'], dtype=object),
 array(['Sense and Sensibility (1995)'], dtype=object),
 array(["Marvin's Room (1996)"], dtype=object),
 array(['In & Out (1997)'], dtype=object),
 array(['Client, The (1994)'], dtype=object),
 array(['Aladdin and the King of Thieves (1996)'], dtype=object),
 array(['Some Like It Hot (1959)'], dtype=object)]

In [48]:
# Converting into a pure list
Movie_Title_List = []
for M in Movie_title:
    print(M)
    MV = list(M)
    Movie_Title_List.append(MV)

['Seven (Se7en) (1995)']
['I.Q. (1994)']
['Santa Clause, The (1994)']
['Free Willy (1993)']
['Sleepless in Seattle (1993)']
['Aladdin (1992)']
['Dances with Wolves (1990)']
['Snow White and the Seven Dwarfs (1937)']
['Spitfire Grill, The (1996)']
['Private Benjamin (1980)']
['Empire Strikes Back, The (1980)']
['Princess Bride, The (1987)']
['Apocalypse Now (1979)']
['GoodFellas (1990)']
['Henry V (1989)']
['Sting, The (1973)']
['Unforgiven (1992)']
['Field of Dreams (1989)']
['Breaking the Waves (1996)']
['Men in Black (1997)']
['Chasing Amy (1997)']
['Sense and Sensibility (1995)']
["Marvin's Room (1996)"]
['In & Out (1997)']
['Client, The (1994)']
['Aladdin and the King of Thieves (1996)']
['Some Like It Hot (1959)']

In [49]:
# Converting into a whole list
Final_Recommended_Movie = list(itertools.chain.from_iterable(Movie_Title_List))
Final_Recommended_Movie

['Seven (Se7en) (1995)',
 'I.Q. (1994)',
 'Santa Clause, The (1994)',
 'Free Willy (1993)',
 'Sleepless in Seattle (1993)',
 'Aladdin (1992)',
 'Dances with Wolves (1990)',
 'Snow White and the Seven Dwarfs (1937)',
 'Spitfire Grill, The (1996)',
 'Private Benjamin (1980)',
 'Empire Strikes Back, The (1980)',
 'Princess Bride, The (1987)',
 'Apocalypse Now (1979)',
 'GoodFellas (1990)',
 'Henry V (1989)',
 'Sting, The (1973)',
 'Unforgiven (1992)',
 'Field of Dreams (1989)',
 'Breaking the Waves (1996)',
 'Men in Black (1997)',
 'Chasing Amy (1997)',
 'Sense and Sensibility (1995)',
 "Marvin's Room (1996)",
 'In & Out (1997)',
 'Client, The (1994)',
 'Aladdin and the King of Thieves (1996)',
 'Some Like It Hot (1959)']