# Python codes for recomendation system to determine ratings based on movie id (item data)

In [1]:
# Import Python libraries
import pandas as pd
import numpy as np

In [2]:
# Load Dataset
Col_names = ['User_id', 'Movie_id', 'Ratings', 'Unique_timestamp']
Ratings = pd.read_csv('ml-100k/u.data', sep = '\t', names = Col_names, encoding = 'latin_1')
Ratings

       User_id  Movie_id  Ratings  Unique_timestamp
0          196       242        3         881250949
1          186       302        3         891717742
2           22       377        1         878887116
3          244        51        2         880606923
4          166       346        1         886397596
...        ...       ...      ...               ...
99995      880       476        3         880175444
99996      716       204        5         879795543
99997      276      1090        1         874795795
99998       13       225        2         882399156
99999       12       203        3         879959583

[100000 rows x 4 columns]

In [3]:
N_Items = Ratings.Movie_id.unique().shape[0]
print(f"There are {N_Items} in the dataset")

There are 1682 in the dataset

In [4]:
# Create pivot table based on user id, movie id and rating
Pivot_table = Ratings.pivot_table (index = 'User_id', columns = 'Movie_id', values = 'Ratings')
Pivot_table

Movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
User_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Replace Nan with 0
Data_matrix = Pivot_table.replace(np.nan, 0)
Data_matrix

Movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
User_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# Find cosine similarity for users
from sklearn.metrics.pairwise import pairwise_distances
Item_similarity = pairwise_distances(Data_matrix.T, metric = 'cosine')
Item_similarity

array([[2.22044605e-16, 5.97617822e-01, 6.69755213e-01, ...,
        1.00000000e+00, 9.52816933e-01, 9.52816933e-01],
       [5.97617822e-01, 2.22044605e-16, 7.26930825e-01, ...,
        1.00000000e+00, 9.21700637e-01, 9.21700637e-01],
       [6.69755213e-01, 7.26930825e-01, 0.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 9.03124947e-01],
       ...,
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [9.52816933e-01, 9.21700637e-01, 1.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [9.52816933e-01, 9.21700637e-01, 9.03124947e-01, ...,
        1.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [7]:
# Score calculation
def prediction(Ratings, Similarity, type = 'item'):
    Item_ratings_mean = Ratings.mean(axis = 1).to_numpy()
    Ratings_diff = Ratings - Item_ratings_mean [:, np.newaxis]
    Predict = Ratings.dot(Similarity) / np.array([np.abs(Similarity).sum(axis=1)])
    return Predict

In [8]:
# Prediction table
Item_prediction = prediction(Data_matrix, Item_similarity, type = 'item')
Item_prediction

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
User_id,,,,,,,,,,,,,,,,,,,,,
1,0.446278,0.475473,0.505938,0.443633,0.512667,0.547939,0.446243,0.463059,0.474916,0.515821,...,0.580579,0.576202,0.582478,0.582478,0.575717,0.588155,0.588155,0.588155,0.573107,0.566696
2,0.108544,0.132957,0.125589,0.124932,0.131178,0.129005,0.110883,0.122223,0.109599,0.121525,...,0.135490,0.136546,0.134829,0.134829,0.134108,0.134458,0.134458,0.134458,0.136576,0.137111
3,0.085685,0.091690,0.087643,0.089966,0.089658,0.089985,0.083492,0.089725,0.085188,0.088331,...,0.089770,0.090506,0.086261,0.086261,0.089201,0.084659,0.084659,0.084659,0.089768,0.090845
4,0.053693,0.059604,0.058114,0.058364,0.059356,0.061472,0.053374,0.058615,0.055905,0.060601,...,0.061349,0.061686,0.061195,0.061195,0.060693,0.057937,0.057937,0.057937,0.061673,0.062281
5,0.224739,0.229171,0.263280,0.226387,0.259973,0.296529,0.232710,0.237109,0.258581,0.275076,...,0.297628,0.295990,0.299922,0.299922,0.298188,0.302051,0.302051,0.302051,0.293373,0.294309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.092574,0.113870,0.110211,0.112040,0.112768,0.123140,0.098578,0.110839,0.098858,0.118579,...,0.123829,0.124430,0.120776,0.120776,0.121360,0.125056,0.125056,0.125056,0.123470,0.124327
940,0.164358,0.184894,0.196502,0.164884,0.195860,0.209652,0.162840,0.165606,0.171761,0.194536,...,0.217536,0.215515,0.219136,0.219136,0.216173,0.218583,0.218583,0.218583,0.216582,0.216819
941,0.032300,0.045024,0.042924,0.043223,0.047493,0.051077,0.032761,0.042646,0.039399,0.047421,...,0.052762,0.053042,0.052692,0.052692,0.051514,0.053028,0.053028,0.053028,0.051910,0.052280
942,0.157779,0.174095,0.189000,0.163514,0.186140,0.194151,0.164910,0.156970,0.167038,0.181295,...,0.197537,0.194479,0.198479,0.198479,0.197969,0.199793,0.199793,0.199793,0.197394,0.200031
943,0.247672,0.244892,0.282630,0.241440,0.279338,0.335121,0.250015,0.263325,0.273579,0.313885,...,0.336816,0.338652,0.338585,0.338585,0.336956,0.344104,0.344104,0.344104,0.330514,0.331025

# Finding similarity among items

In [9]:
# Selection of input item
Input_items = 34

In [10]:
# Convert user sim table into dataframe
Item_Sim_Table = pd.DataFrame(Item_similarity)
Item_Sim_Table

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,2.220446e-16,5.976178e-01,0.669755,5.450621e-01,0.713286,0.883656,0.379021,0.518886,0.503712,0.726065,...,0.964613,1.0,1.000000,1.000000,0.964613,1.0,1.0,1.0,0.952817,0.952817
1,5.976178e-01,2.220446e-16,0.726931,4.974292e-01,0.681164,0.916437,0.616597,0.662998,0.744748,0.828918,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,0.921701,0.921701
2,6.697552e-01,7.269308e-01,0.000000,6.751336e-01,0.787043,0.893278,0.627079,0.799206,0.726331,0.841896,...,1.000000,1.0,1.000000,1.000000,0.967708,1.0,1.0,1.0,1.000000,0.903125
3,5.450621e-01,4.974292e-01,0.675134,1.110223e-16,0.665761,0.909692,0.510717,0.509764,0.580956,0.747439,...,1.000000,1.0,0.905978,0.905978,0.962391,1.0,1.0,1.0,0.943587,0.924782
4,7.132865e-01,6.811638e-01,0.787043,6.657605e-01,0.000000,0.962701,0.665231,0.740839,0.727552,0.944547,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.000000,0.905789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1678,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1679,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1680,9.528169e-01,9.217006e-01,1.000000,9.435867e-01,1.000000,1.000000,0.948502,0.917967,0.942640,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,0.000000,1.000000
1681,9.528169e-01,9.217006e-01,0.903125,9.247823e-01,0.905789,1.000000,0.948502,1.000000,0.928300,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.000000,0.000000

In [11]:
# Finding similarity for user 34 using cosine table
Sim_Input_Item = Item_Sim_Table[Input_items].sort_values(ascending = True).head(5).index
Sim_Input_Item

Index([34, 77, 246, 1030, 794], dtype='int64')

In [12]:
# Convert the similarity values into a list
Sim_Input_Item = list(Sim_Input_Item)
Sim_Input_Item

[34, 77, 246, 1030, 794]

In [13]:
# Select movie id from ratings table using Similarity_Input_Item
Sim_Movie_UserID_List = []
for Sim_Item in Sim_Input_Item:
    Sim = list(Ratings[Ratings['Movie_id']==Sim_Item]['User_id'])
    Sim_Movie_UserID_List.append(Sim)

In [14]:
len(Sim_Movie_UserID_List)

5

In [15]:
print (Sim_Movie_UserID_List)

[[286, 276, 94, 184, 1, 551, 297], [92, 222, 224, 194, 59, 291, 262, 64, 83, 128, 106, 135, 334, 301, 276, 184, 188, 201, 110, 234, 256, 286, 320, 372, 345, 244, 381, 60, 375, 42, 330, 56, 43, 115, 270, 417, 280, 405, 183, 343, 94, 474, 347, 313, 416, 271, 269, 497, 506, 109, 504, 7, 246, 429, 363, 346, 76, 95, 72, 399, 311, 566, 496, 374, 618, 450, 505, 293, 318, 593, 524, 457, 328, 332, 659, 650, 178, 1, 655, 299, 453, 643, 308, 268, 49, 653, 454, 664, 766, 528, 532, 437, 741, 487, 215, 551, 764, 577, 586, 478, 371, 533, 378, 521, 774, 500, 721, 389, 711, 881, 545, 843, 823, 633, 627, 870, 815, 916, 893, 455, 130, 561, 749, 145, 647, 303, 393, 394, 442, 495, 267, 65, 682, 690, 922, 896, 186, 156, 452, 554, 932, 243, 758, 864, 693, 847, 498, 796, 897, 719, 889], [50, 269, 99, 276, 79, 150, 63, 89, 323, 32, 58, 367, 268, 139, 345, 94, 347, 27, 113, 294, 344, 305, 214, 453, 416, 314, 359, 1, 193, 445, 176, 432, 6, 376, 130, 26, 232, 470, 69, 244, 387, 189, 503, 77, 582, 542, 496, 500, 435, 392, 439, 560, 174, 212, 620, 354, 145, 85, 490, 467, 433, 291, 654, 303, 468, 736, 782, 595, 717, 417, 222, 828, 567, 178, 889, 894, 727, 682, 327, 116, 104, 334, 669, 790, 473, 92, 221, 919, 557, 637, 893, 521, 287, 834, 730, 916, 697, 762, 578, 592, 655, 643, 854, 699, 624, 770, 880, 635, 819, 662, 912, 463, 917, 342, 902, 296, 936, 870, 73, 778, 928, 486, 243, 399], [38, 339, 102, 457, 450, 504, 195, 405, 497, 642, 279, 880, 648, 536, 932, 318, 70, 541, 885, 795], [42, 92, 13, 110, 291, 18, 385, 429, 314, 436, 437, 256, 270, 152, 56, 487, 523, 311, 643, 276, 361, 416, 405, 690, 659, 295, 393, 450, 878, 864, 477, 399, 796, 943, 712, 871, 919, 561, 655, 846, 904, 642, 883, 130, 934, 880]]

In [16]:
# Convert all the lists as a single list
import itertools
Sim_Movie_UserID_Single_List = list(itertools.chain.from_iterable(Sim_Movie_UserID_List))

In [17]:
len(Sim_Movie_UserID_Single_List)

348

In [18]:
Sim_Movie_UserID_Single_List

[286,
 276,
 94,
 184,
 1,
 551,
 297,
 92,
 222,
 224,
 194,
 59,
 291,
 262,
 64,
 83,
 128,
 106,
 135,
 334,
 301,
 276,
 184,
 188,
 201,
 110,
 234,
 256,
 286,
 320,
 372,
 345,
 244,
 381,
 60,
 375,
 42,
 330,
 56,
 43,
 115,
 270,
 417,
 280,
 405,
 183,
 343,
 94,
 474,
 347,
 313,
 416,
 271,
 269,
 497,
 506,
 109,
 504,
 7,
 246,
 429,
 363,
 346,
 76,
 95,
 72,
 399,
 311,
 566,
 496,
 374,
 618,
 450,
 505,
 293,
 318,
 593,
 524,
 457,
 328,
 332,
 659,
 650,
 178,
 1,
 655,
 299,
 453,
 643,
 308,
 268,
 49,
 653,
 454,
 664,
 766,
 528,
 532,
 437,
 741,
 487,
 215,
 551,
 764,
 577,
 586,
 478,
 371,
 533,
 378,
 521,
 774,
 500,
 721,
 389,
 711,
 881,
 545,
 843,
 823,
 633,
 627,
 870,
 815,
 916,
 893,
 455,
 130,
 561,
 749,
 145,
 647,
 303,
 393,
 394,
 442,
 495,
 267,
 65,
 682,
 690,
 922,
 896,
 186,
 156,
 452,
 554,
 932,
 243,
 758,
 864,
 693,
 847,
 498,
 796,
 897,
 719,
 889,
 50,
 269,
 99,
 276,
 79,
 150,
 63,
 89,
 323,
 32,
 58,
 367,
 268,
 139,
 345,
 94,
 347,
 27,
 113,
 294,
 344,
 305,
 214,
 453,
 416,
 314,
 359,
 1,
 193,
 445,
 176,
 432,
 6,
 376,
 130,
 26,
 232,
 470,
 69,
 244,
 387,
 189,
 503,
 77,
 582,
 542,
 496,
 500,
 435,
 392,
 439,
 560,
 174,
 212,
 620,
 354,
 145,
 85,
 490,
 467,
 433,
 291,
 654,
 303,
 468,
 736,
 782,
 595,
 717,
 417,
 222,
 828,
 567,
 178,
 889,
 894,
 727,
 682,
 327,
 116,
 104,
 334,
 669,
 790,
 473,
 92,
 221,
 919,
 557,
 637,
 893,
 521,
 287,
 834,
 730,
 916,
 697,
 762,
 578,
 592,
 655,
 643,
 854,
 699,
 624,
 770,
 880,
 635,
 819,
 662,
 912,
 463,
 917,
 342,
 902,
 296,
 936,
 870,
 73,
 778,
 928,
 486,
 243,
 399,
 38,
 339,
 102,
 457,
 450,
 504,
 195,
 405,
 497,
 642,
 279,
 880,
 648,
 536,
 932,
 318,
 70,
 541,
 885,
 795,
 42,
 92,
 13,
 110,
 291,
 18,
 385,
 429,
 314,
 436,
 437,
 256,
 270,
 152,
 56,
 487,
 523,
 311,
 643,
 276,
 361,
 416,
 405,
 690,
 659,
 295,
 393,
 450,
 878,
 864,
 477,
 399,
 796,
 943,
 712,
 871,
 919,
 561,
 655,
 846,
 904,
 642,
 883,
 130,
 934,
 880]

In [19]:
Unique_UserID_Similar_Item = set(Sim_Movie_UserID_Single_List)

In [20]:
len(Unique_UserID_Similar_Item)

274

In [21]:
# Input movie list compare user watched 
Input_Item_Watched_UserID = list(Ratings[Ratings['Movie_id']==Input_items]['User_id'].values)
print(Input_Item_Watched_UserID)

[286, 276, 94, 184, 1, 551, 297]

In [22]:
# Create a list to show movie id to users
Recom = []
for per_id in Unique_UserID_Similar_Item:
    if (per_id in Input_Item_Watched_UserID):
        pass
    else:
        Recom.append(per_id)

In [23]:
len(Recom)

267

In [24]:
print(sorted(Recom))

[6, 7, 13, 18, 26, 27, 32, 38, 42, 43, 49, 50, 56, 58, 59, 60, 63, 64, 65, 69, 70, 72, 73, 76, 77, 79, 83, 85, 89, 92, 95, 99, 102, 104, 106, 109, 110, 113, 115, 116, 128, 130, 135, 139, 145, 150, 152, 156, 174, 176, 178, 183, 186, 188, 189, 193, 194, 195, 201, 212, 214, 215, 221, 222, 224, 232, 234, 243, 244, 246, 256, 262, 267, 268, 269, 270, 271, 279, 280, 287, 291, 293, 294, 295, 296, 299, 301, 303, 305, 308, 311, 313, 314, 318, 320, 323, 327, 328, 330, 332, 334, 339, 342, 343, 344, 345, 346, 347, 354, 359, 361, 363, 367, 371, 372, 374, 375, 376, 378, 381, 385, 387, 389, 392, 393, 394, 399, 405, 416, 417, 429, 432, 433, 435, 436, 437, 439, 442, 445, 450, 452, 453, 454, 455, 457, 463, 467, 468, 470, 473, 474, 477, 478, 486, 487, 490, 495, 496, 497, 498, 500, 503, 504, 505, 506, 521, 523, 524, 528, 532, 533, 536, 541, 542, 545, 554, 557, 560, 561, 566, 567, 577, 578, 582, 586, 592, 593, 595, 618, 620, 624, 627, 633, 635, 637, 642, 643, 647, 648, 650, 653, 654, 655, 659, 662, 664, 669, 682, 690, 693, 697, 699, 711, 712, 717, 719, 721, 727, 730, 736, 741, 749, 758, 762, 764, 766, 770, 774, 778, 782, 790, 795, 796, 815, 819, 823, 828, 834, 843, 846, 847, 854, 864, 870, 871, 878, 880, 881, 883, 885, 889, 893, 894, 896, 897, 902, 904, 912, 916, 917, 919, 922, 928, 932, 934, 936, 943]

In [25]:
# Cross-checking the list with Unique_MovieID_Similar_User
print(sorted(Unique_UserID_Similar_Item))

[1, 6, 7, 13, 18, 26, 27, 32, 38, 42, 43, 49, 50, 56, 58, 59, 60, 63, 64, 65, 69, 70, 72, 73, 76, 77, 79, 83, 85, 89, 92, 94, 95, 99, 102, 104, 106, 109, 110, 113, 115, 116, 128, 130, 135, 139, 145, 150, 152, 156, 174, 176, 178, 183, 184, 186, 188, 189, 193, 194, 195, 201, 212, 214, 215, 221, 222, 224, 232, 234, 243, 244, 246, 256, 262, 267, 268, 269, 270, 271, 276, 279, 280, 286, 287, 291, 293, 294, 295, 296, 297, 299, 301, 303, 305, 308, 311, 313, 314, 318, 320, 323, 327, 328, 330, 332, 334, 339, 342, 343, 344, 345, 346, 347, 354, 359, 361, 363, 367, 371, 372, 374, 375, 376, 378, 381, 385, 387, 389, 392, 393, 394, 399, 405, 416, 417, 429, 432, 433, 435, 436, 437, 439, 442, 445, 450, 452, 453, 454, 455, 457, 463, 467, 468, 470, 473, 474, 477, 478, 486, 487, 490, 495, 496, 497, 498, 500, 503, 504, 505, 506, 521, 523, 524, 528, 532, 533, 536, 541, 542, 545, 551, 554, 557, 560, 561, 566, 567, 577, 578, 582, 586, 592, 593, 595, 618, 620, 624, 627, 633, 635, 637, 642, 643, 647, 648, 650, 653, 654, 655, 659, 662, 664, 669, 682, 690, 693, 697, 699, 711, 712, 717, 719, 721, 727, 730, 736, 741, 749, 758, 762, 764, 766, 770, 774, 778, 782, 790, 795, 796, 815, 819, 823, 828, 834, 843, 846, 847, 854, 864, 870, 871, 878, 880, 881, 883, 885, 889, 893, 894, 896, 897, 902, 904, 912, 916, 917, 919, 922, 928, 932, 934, 936, 943]

In [26]:
# Cross-checking the list with Input_User_Watched_MovieID
print(sorted(Input_Item_Watched_UserID))

[1, 94, 184, 276, 286, 297, 551]

In [27]:
# Checking common movie list
print(list(set(Unique_UserID_Similar_Item)&set(Input_Item_Watched_UserID)))

[1, 551, 297, 276, 184, 94, 286]

In [28]:
Item_pred = pd.DataFrame(Item_prediction)
Item_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
User_id,,,,,,,,,,,,,,,,,,,,,
1,0.446278,0.475473,0.505938,0.443633,0.512667,0.547939,0.446243,0.463059,0.474916,0.515821,...,0.580579,0.576202,0.582478,0.582478,0.575717,0.588155,0.588155,0.588155,0.573107,0.566696
2,0.108544,0.132957,0.125589,0.124932,0.131178,0.129005,0.110883,0.122223,0.109599,0.121525,...,0.135490,0.136546,0.134829,0.134829,0.134108,0.134458,0.134458,0.134458,0.136576,0.137111
3,0.085685,0.091690,0.087643,0.089966,0.089658,0.089985,0.083492,0.089725,0.085188,0.088331,...,0.089770,0.090506,0.086261,0.086261,0.089201,0.084659,0.084659,0.084659,0.089768,0.090845
4,0.053693,0.059604,0.058114,0.058364,0.059356,0.061472,0.053374,0.058615,0.055905,0.060601,...,0.061349,0.061686,0.061195,0.061195,0.060693,0.057937,0.057937,0.057937,0.061673,0.062281
5,0.224739,0.229171,0.263280,0.226387,0.259973,0.296529,0.232710,0.237109,0.258581,0.275076,...,0.297628,0.295990,0.299922,0.299922,0.298188,0.302051,0.302051,0.302051,0.293373,0.294309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.092574,0.113870,0.110211,0.112040,0.112768,0.123140,0.098578,0.110839,0.098858,0.118579,...,0.123829,0.124430,0.120776,0.120776,0.121360,0.125056,0.125056,0.125056,0.123470,0.124327
940,0.164358,0.184894,0.196502,0.164884,0.195860,0.209652,0.162840,0.165606,0.171761,0.194536,...,0.217536,0.215515,0.219136,0.219136,0.216173,0.218583,0.218583,0.218583,0.216582,0.216819
941,0.032300,0.045024,0.042924,0.043223,0.047493,0.051077,0.032761,0.042646,0.039399,0.047421,...,0.052762,0.053042,0.052692,0.052692,0.051514,0.053028,0.053028,0.053028,0.051910,0.052280
942,0.157779,0.174095,0.189000,0.163514,0.186140,0.194151,0.164910,0.156970,0.167038,0.181295,...,0.197537,0.194479,0.198479,0.198479,0.197969,0.199793,0.199793,0.199793,0.197394,0.200031
943,0.247672,0.244892,0.282630,0.241440,0.279338,0.335121,0.250015,0.263325,0.273579,0.313885,...,0.336816,0.338652,0.338585,0.338585,0.336956,0.344104,0.344104,0.344104,0.330514,0.331025

In [29]:
Item_pred[Input_items]

User_id
1      0.572414
2      0.139686
3      0.092378
4      0.062496
5      0.286815
         ...
939    0.122120
940    0.217996
941    0.053046
942    0.198270
943    0.332126
Name: 34, Length: 943, dtype: float64

In [30]:
# Selection of the highest rate movies that would be selected by the item, based on user prediction
Highest_rated = []
Input_Item_Pre = pd.DataFrame(Item_pred[Input_items])
Input_Item_Pred = Input_Item_Pre.T
for Re in Recom:
    Value = Input_Item_Pred[Re].values
    if(Value >= 1):
        Highest_rated.append(Re)

In [31]:
len(Highest_rated)

4

In [33]:
# Check the common Movie list
list(set(Recom) & set(Input_Item_Watched_UserID))

[]